spring.application.name=skillforge-api
server.port=8081
server.address=0.0.0.0
server.servlet.context-path=/api

# === DATASOURCE ===
spring.datasource.url=jdbc:postgresql://localhost:5432/skillforge_db
spring.datasource.username=postgres
spring.datasource.password=Dfrancks15

# === JPA / HIBERNATE ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === APPLICATION ===
app.base-url=/api

# === SFTP CONFIGURATION ===
app.sftp.webhook-secret=fsp_2Xf5LPT9bU15qcqMAUmw1POkKZaqTCuW
app.sftp.host=localhost
app.sftp.port=2022
app.sftp.username=franckd
app.sftp.password=password
app.sftp.base-url=sftp://localhost:2022
app.sftp.root-virtual-path=/uploads

# === JWT Configs ===
app.jwt.secret =be8437917a2c0fc594acacc3819c64ee04bd2f8591937c457085f049f9830047
app.jwt.expiration-ms =86400000
